### ISSUE TITLE
Virification.formatIterator throws exception

### ISSUE THREAD

**Issue by beautybird** [insinfo/fluent_query_builder#1]
This implementstion fails with exception which is a result of Validator.formIterable() that takes a Objects List and return a Strings List.
I'm using Postgresql , dataemaildb field is a varchar .

         Future<DbLayer> _getDbLayer() async {
          connection = DbLayer().connect(connection_settings());
          return connection;
          }

          Future<bool> checkUserExist(String email, String password) async {
             result = await _getDbLayer().then((db) {
             db
                .select().field('dataemaildb').from('datas')
                .where('dataemaildb=?', [email]).limit(1).first().then((val){
                        print(val);
                 });
           }).catchError((e) {
            print('connection error');
             result = false;
             e.toString();
           }).whenComplete(
                   () => connection.timeout(Duration(minutes: 3), onTimeout: () {}));

              return result;
                 }
changing the code to below results in same exception :

	 List<String> stringsList = (db
          .select().field('dataemaildb').from('datas')
           .where('dataemaildb=?', [email]).limit(1).first() as List).cast<String>().toList(growable: true);
      result = (stringsList.length>0 && stringsList !=null ? false : true);

Why Validator.formatIterator returns String List only  ?

and how to make my codes works ?

The Exception :
E/flutter ( 5726): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type 'List dynamic' is not a subtype of type ' List String' in type cast
E/flutter ( 5726): #0      Validator.formatIterable (package:fluent_query_builder/src/models/validator.dart:124:40)
E/flutter ( 5726): #1      Validator.formatArray (package:fluent_query_builder/src/models/validator.dart:128:12)
E/flutter ( 5726): #2      Validator.formatValue (package:fluent_query_builder/src/models/validator.dart:75:16)
E/flutter ( 5726): #3      WhereBlock.buildStr (package:fluent_query_builder/src/models/where_block.dart:72:55)
E/flutter ( 5726): #4      QueryBuilder.toSql (package:fluent_query_builder/src/models/query_builder.dart:103:25)
E/flutter ( 5726): #5      DbLayer.first (package:fluent_query_builder/src/db_layer.dart:191:52)
E/flutter ( 5726): #6      QueryBuilder.first (package:fluent_query_builder/src/models/query_builder.dart:168:12)
E/flutter ( 5726): #7      Persist.checkUserExist.<anonymous closure> (package:beauty_bird/database/database.dart:39:54)

**Comment by insinfo** [comment]
@beautybird 
Hello, thanks for the feedback, it seems to me that there was an error in your code in this part 
```dart 
 db.select().field('dataemaildb').from('datas').where('dataemaildb =?', [Email])...
``` 
should be 
```dart 
 db.select().field('dataemaildb').from('datas').where('dataemaildb=?', 'email@example.com')...
``` 
because you say that the column "dataemaildb" is a varchar field

you can also use whereSafe in 1.1.9 release
```dart 
 db.select().field('dataemaildb').whereSafe('dataemaildb', '=', 'email@example.com')...
``` 

whereSafe is more secure against SQL injection

sorry for the delay in responding but i have been very busy

**Comment by thiagosantoscunha** [comment]
Instead of using `.where('dataemaildb=?', [email])`, try to use this, without array param.
Use the parameter with String type. But, this assignature suport `int `and `bool`.
Date values, also pass a string.

I'm sorry to answer now, as the LIB is new, I wouldn't imagine anyone using it.

**Comment by beautybird** [comment]
Hello,
@insinfo , 1- Ehe email value retrieved dynamically (from a model class which takes the value from the login form UI )and placed in the query..hardcoding one email at a time is not an option. 
2-The stack trace suggest to me that the problem arise from this  onward :  E/flutter ( 5726): #2 Validator.formatValue (package:fluent_query_builder/src/models/validator.dart:75:16)

**Comment by beautybird** [comment]
@thiagosantoscuncha ... actually the select query it comes in the API like this :
 where(String condition, [Object param, String andOr = 'AND']) → QueryBuilder
    override
I tried your way....didn't accept .
Thank you .

**Comment by insinfo** [comment]
I didn't understand exactly what you want to do, but if you want to pass an array or a list of emails just do it this way

```dart
where("email in (?)", "'ins@oi.com','example@xyz.com'", ) 
List<String> arrayEmails = <String>['ins@oi.com','example@xyz.com'];
where("email in (?)", "${arrayEmails.join(',')}", )

```

**Comment by thiagosantoscunha** [comment]
I'm sorry for don't undertand your question. But, i belive of  response of @insinfo can you help.
Gratitude!
