### ISSUE TITLE
How can I override QueryBuilder funcs?

### ISSUE THREAD

**Issue by RosilBelli** [insinfo/fluent_query_builder#10]
What is the best way to just override **firstAsMapFunc** and **getAsMapFunc** to make them return database fields in camelCase?

By the way, you're doing a great package!

**Comment by insinfo** [comment]
@RosilBelli
there is no need to override
you just do a foreach on the returned data and change the case of the map keys

https://stackoverflow.com/questions/22610843/dart-a-nice-way-of-replacing-keys-and-values-in-maps
https://stackoverflow.com/questions/39952335/how-to-convert-map-keys-to-uppercase-in-using-java-8-streams

**Comment by RosilBelli** [comment]
Hi @insinfo 

Thank you for your suggestion, but on our startup, we always create a wrapper around the most important packages and I'd like to set camel case as a default behavior whenever a developer uses those methods.

That's why I asked for a way to set those func attributes. 

Is that possible?

**Comment by insinfo** [comment]
@RosilBelli
I think this is something to be done in your business logic layer and not in the Query Builder API because the API only reflects what is in the database, if in the database you use camelCase for the names of fields and tables this is what the API will show, I particularly use all camelCase in my Postgresql databases. What you can do is an extension as suggested below.

```dart

extension QueryBuilderExtension on QueryBuilder {
  Future<List<Map<String?, dynamic>>> getAsMapCamelCase() async {
    var data = await getAsMap();
    var results = <Map<String, dynamic>>[];
    for (var i = 0; i < data.length; i++) {
      var newMap = <String, dynamic>{};
      for (var key in data[i].keys) {
        if (key != null) {
          newMap[key.camelCase(splitPattern: '_')] = data[i][key];
        }
      }
      results.add(newMap);
    }
    return results;
  }

  Future<Map<String?, dynamic>?> firstAsMapCamelCase() async {
    var data = await firstAsMap();
    if (data != null) {
      var newMap = <String, dynamic>{};
      for (var key in data.keys) {
        if (key != null) {
          newMap[key.camelCase(splitPattern: '_')] = data[key];
        }
      }

      return newMap;
    }
    return data;
  }
}

extension StringCamelCaseExtension on String {
  String capitalize([bool lowerRest = false]) {
    if (length == 0) {
      return '';
    }

    if (lowerRest) {
      return this[0].toUpperCase() + substring(1).toLowerCase();
    } else {
      return this[0].toUpperCase() + substring(1);
    }
  }

  String camelCase({Pattern splitPattern = ' '}) {
    var _splittedString = split(splitPattern);

    if (_splittedString.isEmpty) {
      return '';
    }

    var _firstWord = (_splittedString[0]).toLowerCase();
    var _restWords = _splittedString
        .sublist(1)
        .map((String x) => x.capitalize(true))
        .toList();

    return _firstWord + _restWords.join('');
  }
}

void main() async {
  final comInfo = DBConnectionInfo(
      enablePsqlAutoSetSearchPath: true,
      reconnectIfConnectionIsNotOpen: true,
      host: '192.168.133.13',
      database: 'test',
      driver: ConnectionDriver.pgsql,
      port: 5432,
      username: 'sisadmin',
      password: 's1sadm1n',
      charset: 'utf8',
      setNumberOfProcessorsFromPlatform: false,
      numberOfProcessors: 1,
      useSSL: false //new option
      );

  final db = await DbLayer().connect(comInfo);

  var result = await db.select().from('products').firstAsMapCamelCase();
  print(result);
  // {id: 1, name: test, price: null, registerDate: 2022-04-11 18:17:45.000Z}
  exit(0);
}

```

NOTE: It seems that this package offers many functions for converting String case .
https://pub.dev/packages/quartet

**Comment by RosilBelli** [comment]
Thank you for your suggestion. 

I think that's going to be a better approach for our needs.
