### ISSUE TITLE
How to substitute values on raw queries?

### ISSUE THREAD

**Issue by RosilBelli** [insinfo/fluent_query_builder#11]
I'm trying to substitute parameters on raw queries but the associated **buildSubstitutionValues** func does not exist. 
Also, I'd like to know where to send the parameters' values. I tried to do that with **setAll** without success.

conn.raw('Select * from person where name = @aName').buildSubstitutionValues().exec();

**Comment by insinfo** [comment]
@RosilBelli 
I haven't had much time to update this pack with new features, but I just updated the pack with the option you wanted.

https://pub.dev/packages/fluent_query_builder

### example

```dart
import 'dart:io';
import 'package:fluent_query_builder/fluent_query_builder.dart';

void main() async {
  final comInfo = DBConnectionInfo(
    enablePsqlAutoSetSearchPath: true,
    reconnectIfConnectionIsNotOpen: true,
    host: '192.168.133.13',
    database: 'test',
    driver: ConnectionDriver.pgsql,
    port: 5432,
    username: 'sisadmin',
    password: 's1sadm1n',
    charset: 'utf8',
    setNumberOfProcessorsFromPlatform: false,
    numberOfProcessors: 1,
  );

  final db = await DbLayer().connect(comInfo);
//Substitution Values
  await db.raw('INSERT INTO products (name,price) VALUES (@name, @price)',
      substitutionValues: {'name': 'iPhone 6S', 'price': 2.50}).exec();

  
  exit(0);
}

```

**Comment by RosilBelli** [comment]
Thank you very much @insinfo !
