### ISSUE TITLE
No option for changing query timeout when using PostgreSQL

### ISSUE THREAD

**Issue by Wishmater** [insinfo/fluent_query_builder#15]
I'm creating a connection to a PosgreSQL database using the method DbLayer().connect(). The problem is I can't find any parameter in the method or the DBConnectionInfo it receives for specifying queryTimeout, and it just always defaults to 30sec.

Diving a bit more in the code, I see PostgreSQLConnection does have a queryTimeoutInSeconds parameter, but it is not used when the connection is created in PostgreSqlExecutor and it just defaults to 30.

It is important in my case to allow queries to run longer, is there a solution for this or at least a workaround I can use?

**Comment by insinfo** [comment]
@Wishmater
I released an update with "timeoutInSeconds" option to resolve your issue

fluent_query_builder 3.4.3 
https://pub.dev/packages/fluent_query_builder

**Comment by Wishmater** [comment]
Thanks for the quick response. It seems to be working fine now.
