### ISSUE TITLE
select leftJoin, rightJoin, innerJoin help me

### ISSUE THREAD

**Issue by luanssd** [insinfo/fluent_query_builder#16]
I am wanting to apply the fluent_query_builder package for Windows application (Database Mariadb). My application needs frequent queries that join tables together, like queries related to leftJoin, rightJoin... ,in the example I'm testing, i want to get some columns in certain tables, but often give me an error, so please help me to solve this problem.

CREATE TABLE `table_01` (
  `id` int(10) UNSIGNED NOT NULL,
  `name` varchar(255) DEFAULT NULL,
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `table_02` (
  `id` int(10) UNSIGNED NOT NULL,
  `idtb1` int(10) UNSIGNED NOT NULL,
  `info` varchar(255) DEFAULT NULL,
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `table_01`(`id`, `name`) VALUES ('11','infomation in table 01')
INSERT INTO `table_02`(`id`, `idtb1`, `info`) VALUES ('22','11','infomation in table 02')

var $result = db .select()
        .fields(['name', 'b.info', 'b.id'])    
        .from('table_01', alias: 'a')
        .leftJoin('table_02', 'a.id', '=', 'b.idtb1', alias: 'b')
        .getAsMap();

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MySqlException 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'info FROM table_01 `a` LEFT JOIN table_02 `b` ON (a.id=b.idtb1) at line 1

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.4.0-33.0.pre.34, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.4)
[√] Android Studio (version 2021.3)
[√] Connected device (2 available)
[√] HTTP Host Availability

**Comment by insinfo** [comment]
@luanssd 
I will test here now and give you a feedback later

**Comment by insinfo** [comment]
@luanssd 
I fixed the bugs that prevented the use of the way you were using it, I published version 4.0.0

fluent_query_builder: ^4.0.0

https://pub.dev/packages/fluent_query_builder


```dart
import 'dart:io';
import 'package:fluent_query_builder/fluent_query_builder.dart';

void main() async {
  //connection information
  final mariadbInfo = DBConnectionInfo(
    reconnectIfConnectionIsNotOpen: true,
    host: 'localhost',
    database: 'banco_teste',
    driver: ConnectionDriver.mysql,
    port: 3306,
    username: 'sisadmin',
    password: 's1sadm1n',
    charset: 'utf8',
    setNumberOfProcessorsFromPlatform: false,
    numberOfProcessors: 1,
  );

  final db = DbLayer();
  try {
    QueryBuilder query;
    dynamic result;
    print('try connect to mariadb');
    await db.connect(mariadbInfo);
    // delete table
    await db.execute('DROP TABLE IF EXISTS `table_01`');
    // create table
    await db.execute('''
CREATE TABLE `table_01` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `test` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=13 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
''');

    // delete table
    await db.execute('DROP TABLE IF EXISTS `table_02`');
    // create table
    await db.execute('''
CREATE TABLE `table_02` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idtb1` int(255) DEFAULT NULL,
  `info` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=23 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
''');

    await db.delete().from('table_01').whereSafe('id', '=', 11).exec();
    await db.delete().from('table_02').whereSafe('id', '=', 22).exec();

    //INSERT INTO table_01(id, name) VALUES ('11','infomation in table 01');
    // INSERT query
    query =
        db.insertGetId().into('table_01').setAll({'id': 11, 'name': 'Isaque'});
    result = await query.exec();
    print('result insert: $result');

    // update query
    query = db
        .update()
        .whereSafe('id', '=', 11)
        .table('table_01')
        .setAll({'test': 'test', 'name': 'Isaque Neves'});

    print('update query sql: ${query.toSql()}');
    result = await query.exec();
    print('result update: $result');

    //INSERT INTO table_02(id, idtb1, info) VALUES ('22','11','infomation in table 02');
    query = db
        .insertGetId()
        .into('table_02')
        .setAll({'id': 22, '`idtb1`': 12, 'info': 'infomation in table 02'});

    result = await query.exec();
    print('result insert: $result');

    // select query
    query = db
        .select()
        .fields(['name', 'b.info', 'b.id'])
        .from('table_01', alias: 'a')
        .leftJoin('table_02', 'a.id', '=', 'b.`idtb1`', alias: 'b')
        .offset(0)
        .limit(100)
        .group('b.info')
        .order('b.info');

    print('select query sql: ${query.toSql()}');
    result = await query.getAsMap();

    print('result: $result');
  } catch (e, s) {
    print('catch connect $e $s');
  }

  exit(0);
}
// output
// PS C:\MyDartProjects\fluent_query_builder> dart .\example\example_mariadb.dart
// try connect to mariadb
// result insert: [[11]]
// update query sql: UPDATE table_01 SET test = @test, name = @name WHERE  id  =  @id 
// result update: []
// result insert: [[22]]
// select query sql: SELECT name, b.info, b.id FROM table_01 AS a LEFT JOIN table_02 AS b ON (a.id=b.`idtb1`) GROUP BY b.info ORDER BY b.info asc LIMIT 100 OFFSET 0
// result: [{name: Isaque Neves, info: null, id: null}]
```

**Comment by luanssd** [comment]
> @luanssd Tôi đã sửa các lỗi ngăn cản việc sử dụng theo cách bạn đang sử dụng, tôi đã xuất bản phiên bản 4.0.0
> 
> thông thạo_query_builder: ^ 4.0.0
> 
> https://pub.dev/packages/fluent_query_builder
> 
> ```dart
> import 'dart:io';
> import 'package:fluent_query_builder/fluent_query_builder.dart';
> 
> void main() async {
>   //connection information
>   final mariadbInfo = DBConnectionInfo(
>     reconnectIfConnectionIsNotOpen: true,
>     host: 'localhost',
>     database: 'banco_teste',
>     driver: ConnectionDriver.mysql,
>     port: 3306,
>     username: 'sisadmin',
>     password: 's1sadm1n',
>     charset: 'utf8',
>     setNumberOfProcessorsFromPlatform: false,
>     numberOfProcessors: 1,
>   );
> 
>   final db = DbLayer();
>   try {
>     QueryBuilder query;
>     dynamic result;
>     print('try connect to mariadb');
>     await db.connect(mariadbInfo);
>     // delete table
>     await db.execute('DROP TABLE IF EXISTS `table_01`');
>     // create table
>     await db.execute('''
> CREATE TABLE `table_01` (
>   `id` int(11) NOT NULL AUTO_INCREMENT,
>   `name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
>   `test` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
>   PRIMARY KEY (`id`)
> ) ENGINE=MyISAM AUTO_INCREMENT=13 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
> ''');
> 
>     // delete table
>     await db.execute('DROP TABLE IF EXISTS `table_02`');
>     // create table
>     await db.execute('''
> CREATE TABLE `table_02` (
>   `id` int(11) NOT NULL AUTO_INCREMENT,
>   `idtb1` int(255) DEFAULT NULL,
>   `info` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
>   PRIMARY KEY (`id`)
> ) ENGINE=MyISAM AUTO_INCREMENT=23 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
> ''');
> 
>     await db.delete().from('table_01').whereSafe('id', '=', 11).exec();
>     await db.delete().from('table_02').whereSafe('id', '=', 22).exec();
> 
>     //INSERT INTO table_01(id, name) VALUES ('11','infomation in table 01');
>     // INSERT query
>     query =
>         db.insertGetId().into('table_01').setAll({'id': 11, 'name': 'Isaque'});
>     result = await query.exec();
>     print('result insert: $result');
> 
>     // update query
>     query = db
>         .update()
>         .whereSafe('id', '=', 11)
>         .table('table_01')
>         .setAll({'test': 'test', 'name': 'Isaque Neves'});
> 
>     print('update query sql: ${query.toSql()}');
>     result = await query.exec();
>     print('result update: $result');
> 
>     //INSERT INTO table_02(id, idtb1, info) VALUES ('22','11','infomation in table 02');
>     query = db
>         .insertGetId()
>         .into('table_02')
>         .setAll({'id': 22, '`idtb1`': 12, 'info': 'infomation in table 02'});
> 
>     result = await query.exec();
>     print('result insert: $result');
> 
>     // select query
>     query = db
>         .select()
>         .fields(['name', 'b.info', 'b.id'])
>         .from('table_01', alias: 'a')
>         .leftJoin('table_02', 'a.id', '=', 'b.`idtb1`', alias: 'b')
>         .offset(0)
>         .limit(100)
>         .group('b.info')
>         .order('b.info');
> 
>     print('select query sql: ${query.toSql()}');
>     result = await query.getAsMap();
> 
>     print('result: $result');
>   } catch (e, s) {
>     print('catch connect $e $s');
>   }
> 
>   exit(0);
> }
> // output
> // PS C:\MyDartProjects\fluent_query_builder> dart .\example\example_mariadb.dart
> // try connect to mariadb
> // result insert: [[11]]
> // update query sql: UPDATE table_01 SET test = @test, name = @name WHERE  id  =  @id 
> // result update: []
> // result insert: [[22]]
> // select query sql: SELECT name, b.info, b.id FROM table_01 AS a LEFT JOIN table_02 AS b ON (a.id=b.`idtb1`) GROUP BY b.info ORDER BY b.info asc LIMIT 100 OFFSET 0
> // result: [{name: Isaque Neves, info: null, id: null}]
> ```

I have updated and it is as expected
Thank you very much, wish you good health!

**Comment by insinfo** [comment]
I just published version 5.5.0 with some fixes and improvements, let me know if it's working for you.


general refactoring, to put double quotes " for Postgresql and ` for MySQL in the table field names for Insert and Update and.
BREAK CHANGE: now you have to pass the DBConnectionInfo class instance to the DbLayer class constructor, optionally you can override DBConnectionInfo in connect() method.
bug fix in automated tests

fix bugs
BREAK CHANGE: the "where" method now puts the quotes envolving the parameter value automatically OLD: where('nome ilike ?', "'%isaque%'") NEW: where('nome ilike ?', '%isaque%') change optional parameters to named parameters of whereRaw whereRaw('b.info ilike @info', andOr: 'AND', substitutionValues: {'info': "%Sant'Ana%"})

```dart
import 'dart:io';
import 'package:fluent_query_builder/fluent_query_builder.dart';

void main() async {
  //connection information
  final mariadbInfo = DBConnectionInfo(
    reconnectIfConnectionIsNotOpen: true,
    host: 'localhost',
    database: 'banco_teste',
    driver: ConnectionDriver.mysql,
    port: 3306,
    username: 'sisadmin',
    password: 's1sadm1n',
    charset: 'utf8',
    setNumberOfProcessorsFromPlatform: false,
    numberOfProcessors: 1,
  );

  final db = DbLayer(mariadbInfo);
  try {
    QueryBuilder query;
    dynamic result;
    print('try connect to mariadb');
    await db.connect();
    // delete table
    await db.execute('DROP TABLE IF EXISTS `table_01`');
    // create table
    await db.execute('''
CREATE TABLE `table_01` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `test` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=13 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
''');

    // delete table
    await db.execute('DROP TABLE IF EXISTS `table_02`');
    // create table
    await db.execute('''
CREATE TABLE `table_02` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idtb1` int(255) DEFAULT NULL,
  `info` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=23 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
''');

    await db.delete().from('table_01').whereSafe('id', '=', 11).exec();
    await db.delete().from('table_02').whereSafe('id', '=', 22).exec();

    //INSERT INTO table_01(id, name) VALUES ('11','infomation in table 01');
    // INSERT query
    query =
        db.insertGetId().into('table_01').setAll({'id': 11, 'name': 'Isaque'});
    print('insert query sql: ${query.toSql()}');
    result = await query.exec();
    print('result insert: $result');

    // update query
    query = db
        .update()
        .whereSafe('id', '=', 11)
        .table('table_01')
        .setAll({'test': null, 'name': 'Isaque Neves', 'date': DateTime.now()});

    print('update query sql: ${query.toSql()}');
    result = await query.exec();
    print('result update: $result');

    //INSERT INTO table_02(id, idtb1, info) VALUES ('22','11','infomation in table 02');
    query = db
        .insertGetId()
        .into('table_02')
        .setAll({'id': 22, 'idtb1': 11, 'info': 'infomation in table 04'});
    print('insert query sql: ${query.toSql()}');
    result = await query.exec();
    print('result insert: $result');

    query = db
        .update()
        .whereSafe('id', '=', 22)
        .table('table_02')
        .setAll({'idtb1': 11, 'info': 'infomation in table 02'});
    result = await query.exec();
    print('result update: $result');

    // select query
    query = db
        .select()
        .fields(['name', 'b.info', 'b.id'])
        .from('table_01', alias: 'a')
        .leftJoin('table_02', 'a.id', '=', 'b.idtb1', alias: 'b')
        .offset(0)
        .limit(100)
        //  .group('b.info')
        .order('b.info');

    print('select query sql: ${query.toSql()}');
    result = await query.getAsMap();

    print('result: $result');
  } catch (e, s) {
    print('catch connect $e $s');
  }

  exit(0);
}

```


```console
PS C:\MyDartProjects\fluent_query_builder> dart .\example\example_mariadb.dart
try connect to mariadb
insert query sql: INSERT INTO table_01 (`id`, `name`) VALUES (?, ?)
result insert: [[11]]
update query sql: UPDATE table_01 SET `test` = ?, `name` = ?, `date` = ? WHERE  id  =  ?
result update: []
insert query sql: INSERT INTO table_02 (`id`, `idtb1`, `info`) VALUES (?, ?, ?)
result insert: [[22]]
result update: []
select query sql: SELECT name, b.info, b.id FROM table_01 AS a LEFT JOIN table_02 AS b ON (a.id=b.idtb1) ORDER BY b.info asc LIMIT 100 OFFSET 0
result: [{name: Isaque Neves, info: infomation in table 02, id: 22}]
PS C:\MyDartProjects\fluent_query_builder> 
```
https://pub.dev/packages/fluent_query_builder

**Comment by luanssd** [comment]
I haven't gone into depth yet as my application is still under development.
I appreciate your enthusiasm in improving and fixing bugs, hope to receive many improvements and timely fixes when discovered.
By the way, I have a query with non-fixed conditions, for example:

```
List Where_value = [];
Where_value.add({'nome like %Sant\'Ana%'});
Where_value.add({'OR telefone like (22) 2771-6265'});
//SELECT
db.select()
	.from('pessoas')
	.wheremultiple(Where_value) 
	.getAsMap()
	.then((result) => print('mysql select $result'));
  });
```

Because I think many people will customize the conditions when there is a value to query
For example:
```
List Where_value = [];
Where_value.add({'Where nome like %Sant\'Ana%'});

String valuetelefone = valuetelefone.txt;
if(valuetelefone != '')
{
Where_value.add({"OR telefone like  '${valuetelefone}' "});
}

String valuegroup = valuegroup.txt;
if(valuegroup != '')
{
Where_value.add({"AND group ='${valuegroup}' "});
}

//SELECT
db.select()
	.from('pessoas')
	.wheremultiple(Where_value) 
	.getAsMap()
	.then((result) => print('mysql select $result'));
  });
```
Please try to research whether it is suitable to supplement

**Comment by insinfo** [comment]
@luanssd

what you are suggesting is already possible.

```dart

var query = db.select().from('pessoas');

query.whereSafe('name', 'like', '%Sant\'Ana%');

String valuetelefone = valuetelefone.txt;
if(valuetelefone != '')
{
    query.whereSafe('telefone', 'like', valuetelefone,'OR ');
}

String valuegroup = valuegroup.txt;
if(valuegroup != '')
{
    query.whereSafe('"group"', 'like', valuegroup,'AND');
}


query.getAsMap()
.then((result) => print('mysql select $result'));
 
```

so I edited your code to demonstrate that it's possible, but I didn't compile this code, there might be typos.
