### ISSUE TITLE
Update query future error

### ISSUE THREAD

**Issue by beautybird** [insinfo/fluent_query_builder#5]
1 This is a flutter  form textField  with onPressed function:

               bool updateBuyerBool;

                 onPressed: () {
                     if (_buyerAccount_formKey.currentState.validate()) {
                       formKey.currentState.save();
             
                       Model().updateBuyerDetailsModel(textOne, textTwo).then((boolValue){
                            if(boolValue == true){
                                      .........
			   }else{
                                         ......
			    }
                    }

2- This is the Model class :-

              Future<bool> updateBuyerDetailsModel(String compCity, String compState) async {
                   await Persist_Entries().updateBuyerDetails(compCity, 
                          compState,Model.emailFieldString).then((valueBool) {
     
	                   updateBuyerBool = valueBool;
                     }).catchError((err) {
                           updateBuyerBool = false;
                           err.toString();
                     }).whenComplete(() => null);
             
            return updateBuyerBool;        
          }

3- This is the Database class :-

             Future<bool> updateBuyerDetails(String city, String state,String email) async {
                    Map<String, dynamic> fieldsMap = {
                                'cityFiledDB': city,
                                'stateFieldDB': state,
                     };
             await DbLayer().connect(dbLayerConnSettings()).then((db) {
          db
          .update()
          .whereSafe('emailFieldDB', '=', email)
          .table('usersData')
          .setAll(fieldsMap)
          .exec()                                                            //line 220
          .then((result) {						//this first debug point
        updateBuyerBool = (result.isNotEmpty == true && result.length >0  ? true : false);   // second debug point
        print('updateBuyerBool is $updateBuyerBool');
      }).catchError((err) {     //third debug point    ...line 224
        updateBuyerBool = false;
        err.toString();
      }).whenComplete(() => Timer(Duration(minutes: 2), () {
                db.close();
              }));
    }).catchError(() {
      updateBuyerBool = false;
    }).whenComplete(() => null);

    return updateBuyerBool;
  }

The 2nd debug point gives updateBuyerBool a false value ...but then it jumps to invoke the 3rd debug point !
Why the future returns with false then error though DbLayer.exec (db_layer.dart:1) seems to me invoked with no error ?

below is the stack :-

Persist_Entries.updateBuyerDetails.<anonymous closure>.<anonymous closure> (database_mysql.dart:224)
_rootRunUnary (zone.dart:1134)
_CustomZone.runUnary (zone.dart:1031)
_FutureListener.handleValue (future_impl.dart:139)
Future._propagateToListeners.handleValueCallback (future_impl.dart:680)
Future._propagateToListeners (future_impl.dart:709)
Future._completeWithValue (future_impl.dart:524)
_AsyncAwaitCompleter.complete (async_patch.dart:32)
_completeOnAsyncReturn (async_patch.dart:290)
DbLayer.exec (db_layer.dart:1)
<asynchronous gap>
DbLayer.exec (db_layer.dart:1)
_Closure.call (function.dart:1)
Update._execFunc (update.dart:1)
QueryBuilder.exec (query_builder.dart:158)
Persist_Entries.updateBuyerDetails.<anonymous closure> (database_mysql.dart:220)
_rootRunUnary (zone.dart:1134)
_rootRunUnary (zone.dart:1)
_CustomZone.runUnary (zone.dart:1031)
_FutureListener.handleValue (future_impl.dart:139)
Future._propagateToListeners.handleValueCallback (future_impl.dart:680)
Future._propagateToListeners (future_impl.dart:709)
Future._completeWithValue (future_impl.dart:524)
_AsyncAwaitCompleter.complete (async_patch.dart:32)
_completeOnAsyncReturn (async_patch.dart:290)
DbLayer.connect (db_layer.dart:1)
<asynchronous gap>
Persist_Entries.updateBuyerDetails (database_mysql.dart:213)

**Comment by insinfo** [comment]
the exec () method returns a list with list, if it is an update()... it will return an empty list, if it is an insertGetId() .. it will return a list with list with one item that will be the id,

you do not need to check the result of the update method because if you do not throw an exception, it was saved in the database successfully

Below is an example of code that I use for insertion and update in production.

```dart
   @override
  Future<Jornal> createFromMap(Map<String, dynamic> entityMap) async {
    final item = Jornal.fromMap(entityMap);
    //item.dataCadastro = DateTime.now();
    item.validate();
    final query = db.insertGetId().into(item.tableName);
    query.setAll(item.toInsert());
    final result = await query.exec();
    item.id = int.tryParse(result[0][0].toString());
    return item;
  }

Future<Jornal> updateFromMapWithFiles(
      Map<String, dynamic> entityMap, UploadedFile jornalPDF, UploadedFile imagem) async {
    final item = Jornal.fromMap(entityMap);
    item.dataCadastro = DateTime.now();
    item.validate();
    //
    final fileService = FileService();
    var fileNameJornalPDF = '', fileNameImagem = '';
    final atualNameJornalPDF = item.fisicalFilename;
    final atualNameImagem = item.imagem;
    //await db.transaction((ctx) async { //});

    //deleta jornal anterior
    await fileService.deleteIfExist('${AppConfig.storagePath}/${atualNameJornalPDF}');
    //deleta imagem anterior
    await fileService.deleteIfExist('${AppConfig.storagePath}/${atualNameImagem}');

    try {
      fileNameJornalPDF = await fileService.create(jornalPDF, '${AppConfig.storagePath}', randFileName: true);
      fileNameImagem = await fileService.create(imagem, '${AppConfig.storagePath}', randFileName: true);
      item.fisicalFilename = fileNameJornalPDF;
      item.originalFilename = jornalPDF.filename;
      item.imagem = fileNameImagem;
      item.link = '${AppConfig.storageWebPath}/$fileNameJornalPDF';
      final query = db.update().table(item.tableName).whereSafe(Jornal.ID_KEY, '=', item.id);
      query.setAll(item.toInsert());
      await query.exec();
    } catch (e) {
      await fileService.deleteIfExist('${AppConfig.storagePath}/$fileNameJornalPDF');
      await fileService.deleteIfExist('${AppConfig.storagePath}/$fileNameImagem');
      rethrow;
    }

    return item;
  }

```

**Comment by insinfo** [comment]
I believe that it is not necessary for you to call db.close (); because the connection will be closed when the DBLayer instance is collected by the garbage collector or when it is equal to null
