### ISSUE TITLE
Builder creates wrong sql statements

### ISSUE THREAD

**Issue by zimbado** [insinfo/fluent_query_builder#6]
I have a problem with some of your query builders. While the `Select` block and also the `Update` block, with the `updateSingle()` function works fine, the `Insert` and `Delete` block produce wrong sql statements for my MariaDB database. It doesn't matter if I use the `putSingle` / `putSingleGetId` function or build a query like `db.insert().into('table').setAll(model.toMap()).exec()`, I get the same wrong sql query. The problem is, that the produced sql query puts the table name, field names inside quotation marks like 'INSERT INTO "table" ("id", "Type", "Identifier", "Name") VALUES ("1", "FLOAT", "THETA", "Description")' but what I need and what is working is 'INSERT INTO table (id, Type, Identifier, Name) VALUES ("1", "FLOAT", "THETA", "Description")'. I already tried to set `QueryBuilderOptions` like `db.options.autoQuoteFieldNames = false` and `db.options.autoQuoteTableNames = false` after connecting to my database, but this have not changed anything. Can you tell me how to use the options properly or if their is any bug? If you need any other information, please let me know

**Comment by insinfo** [comment]
Hello, I've been very busy these days, I'll try to help you, come on.
The first thing is that the ORM part (ie the putSingle <Type> (Object) updateSingle <Type> (Object), fetchAll <Type> (), deleteSingle <Type> (Object) methods of the library is not finished and possibly it will not work for all use cases at this time.

I use this library in several of my production projects, but without the ORM part (ie putSingle <Type> (Object) updateSingle <Type> (Object), fetchAll <Type> (), deleteSingle <Type> (Object) )

I use only the common SQL statements and clauses methods:

```dart
  // MySQL connection information
  final mysqlCom = DBConnectionInfo (
    host: 'localhost',
    database: 'test_bank',
    driver: ConnectionDriver.mysql,
    port: 3306,
     username: 'user',
    password: 'pass',
    charset: 'utf8',
  );

  DbLayer (). Connect (mysqlCom) .then ((db) {
    // mysql insert
    db
        .insert ()
        .into ('people')
        .set ('name', 'Isaque Neves Sant \' Ana ')
        .set ('phone', '(22) 2771-6265')
        .exec ()
        .then ((result) => print ('mysql insert $ result'));

    // mysql update
    db
        .update ()
        .table ('people')
        .set ('name', 'John')
        .where ('id =?', 13)
        .exec ()
        .then ((result) => print ('mysql update $ result'));

    // mysql update with setAll
    db
        .update ()
        .whereSafe ('id', '=', 13)
        .table ('people')
        .setAll ({
          'name': 'Jon Doe',
          'phone': '171171171',
        })
        .exec ()
        .then ((result) => print ('mysql update with setAll $ result'));

    // mysql delete
    db.delete (). from ('people')
    .where ('id =?', 14)
    .exec ()
    .then ((result) => print ('mysql delete $ result'));

    // mysql select
    db
        .select ()
        //.fields( Renda'login ',' SystemID ',' s.sigla '])
        //.fieldRaw('SELECT COUNT (*) ')
        .from ('people')
        .whereSafe ('name', 'like', '% Sant \' Ana% ')
        //.limit(1)
        .firstAsMap ()
        .then ((result) => print ('mysql select $ result'));

    // mysql raw query SELECT * FROM `people` or SELECT COUNT (*) FROM people
    db
        .raw ("SELECT * FROM` people` ")
        .firstAsMap ()
        .then ((result) => print ('mysql raw $ result'));
        
    // mysql count records
    db
        .select ()
        .from ('people')
        .orWhereSafe ('name', 'like', '% Sant \' Ana% ')
        .orWhereSafe ('id', '<', 20)
        .count ()
        .then ((result) => print ('mysql count $ result'));
  });

```

As can be demonstrated in the README at https://pub.dev/packages/fluent_query_builder

I use PostgreSQL more than MariaDB in my applications, although I have in production several applications that read MariaDB, at the beginning of library development I tested a lot on MariaDB also more as I am not using UPDATE / INSERTE / DELETE operations in mariadb it may be that there is a bug, show me your code so I can do some tests.
